// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bftsmart.proto

/*
Package orderer is a generated protocol buffer package.

It is generated from these files:
	bftsmart.proto

It has these top-level messages:
	BftSmartMessage
	BftSmartMessageRegular
	BftSmartMessageTimeToCut
	BftSmartMessageConnect
	BftSmartMessageSynchronize
	BftProxyMessageConnect
	BftSmartMessageMetadata
	BftSmartProxy
	SendResponse
	RecvResponse
*/
package orderer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BftSmartMessageRegular_Class int32

const (
	BftSmartMessageRegular_UNKNOWN BftSmartMessageRegular_Class = 0
	BftSmartMessageRegular_NORMAL  BftSmartMessageRegular_Class = 1
	BftSmartMessageRegular_CONFIG  BftSmartMessageRegular_Class = 2
)

var BftSmartMessageRegular_Class_name = map[int32]string{
	0: "UNKNOWN",
	1: "NORMAL",
	2: "CONFIG",
}
var BftSmartMessageRegular_Class_value = map[string]int32{
	"UNKNOWN": 0,
	"NORMAL":  1,
	"CONFIG":  2,
}

func (x BftSmartMessageRegular_Class) String() string {
	return proto.EnumName(BftSmartMessageRegular_Class_name, int32(x))
}
func (BftSmartMessageRegular_Class) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0}
}

type BftSmartMessageSynchronize_Class int32

const (
	BftSmartMessageSynchronize_UNKNOWN  BftSmartMessageSynchronize_Class = 0
	BftSmartMessageSynchronize_REQUEST  BftSmartMessageSynchronize_Class = 1
	BftSmartMessageSynchronize_RESPONSE BftSmartMessageSynchronize_Class = 2
)

var BftSmartMessageSynchronize_Class_name = map[int32]string{
	0: "UNKNOWN",
	1: "REQUEST",
	2: "RESPONSE",
}
var BftSmartMessageSynchronize_Class_value = map[string]int32{
	"UNKNOWN":  0,
	"REQUEST":  1,
	"RESPONSE": 2,
}

func (x BftSmartMessageSynchronize_Class) String() string {
	return proto.EnumName(BftSmartMessageSynchronize_Class_name, int32(x))
}
func (BftSmartMessageSynchronize_Class) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{4, 0}
}

// bftsmartMessage is a wrapper type for the messages
// that the bftsmart-based orderer deals with.
type BftSmartMessage struct {
	// Types that are valid to be assigned to Type:
	//	*BftSmartMessage_Regular
	//	*BftSmartMessage_TimeToCut
	//	*BftSmartMessage_Connect
	//	*BftSmartMessage_Synchronize
	//	*BftSmartMessage_BftProxyConnect
	Type      isBftSmartMessage_Type `protobuf_oneof:"Type"`
	ChannelId string                 `protobuf:"bytes,6,opt,name=channelId" json:"channelId,omitempty"`
	Sender    string                 `protobuf:"bytes,7,opt,name=sender" json:"sender,omitempty"`
	SendIndex uint64                 `protobuf:"varint,8,opt,name=sendIndex" json:"sendIndex,omitempty"`
}

func (m *BftSmartMessage) Reset()                    { *m = BftSmartMessage{} }
func (m *BftSmartMessage) String() string            { return proto.CompactTextString(m) }
func (*BftSmartMessage) ProtoMessage()               {}
func (*BftSmartMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isBftSmartMessage_Type interface {
	isBftSmartMessage_Type()
}

type BftSmartMessage_Regular struct {
	Regular *BftSmartMessageRegular `protobuf:"bytes,1,opt,name=regular,oneof"`
}
type BftSmartMessage_TimeToCut struct {
	TimeToCut *BftSmartMessageTimeToCut `protobuf:"bytes,2,opt,name=time_to_cut,json=timeToCut,oneof"`
}
type BftSmartMessage_Connect struct {
	Connect *BftSmartMessageConnect `protobuf:"bytes,3,opt,name=connect,oneof"`
}
type BftSmartMessage_Synchronize struct {
	Synchronize *BftSmartMessageSynchronize `protobuf:"bytes,4,opt,name=synchronize,oneof"`
}
type BftSmartMessage_BftProxyConnect struct {
	BftProxyConnect *BftProxyMessageConnect `protobuf:"bytes,5,opt,name=bftProxyConnect,oneof"`
}

func (*BftSmartMessage_Regular) isBftSmartMessage_Type()         {}
func (*BftSmartMessage_TimeToCut) isBftSmartMessage_Type()       {}
func (*BftSmartMessage_Connect) isBftSmartMessage_Type()         {}
func (*BftSmartMessage_Synchronize) isBftSmartMessage_Type()     {}
func (*BftSmartMessage_BftProxyConnect) isBftSmartMessage_Type() {}

func (m *BftSmartMessage) GetType() isBftSmartMessage_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *BftSmartMessage) GetRegular() *BftSmartMessageRegular {
	if x, ok := m.GetType().(*BftSmartMessage_Regular); ok {
		return x.Regular
	}
	return nil
}

func (m *BftSmartMessage) GetTimeToCut() *BftSmartMessageTimeToCut {
	if x, ok := m.GetType().(*BftSmartMessage_TimeToCut); ok {
		return x.TimeToCut
	}
	return nil
}

func (m *BftSmartMessage) GetConnect() *BftSmartMessageConnect {
	if x, ok := m.GetType().(*BftSmartMessage_Connect); ok {
		return x.Connect
	}
	return nil
}

func (m *BftSmartMessage) GetSynchronize() *BftSmartMessageSynchronize {
	if x, ok := m.GetType().(*BftSmartMessage_Synchronize); ok {
		return x.Synchronize
	}
	return nil
}

func (m *BftSmartMessage) GetBftProxyConnect() *BftProxyMessageConnect {
	if x, ok := m.GetType().(*BftSmartMessage_BftProxyConnect); ok {
		return x.BftProxyConnect
	}
	return nil
}

func (m *BftSmartMessage) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *BftSmartMessage) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *BftSmartMessage) GetSendIndex() uint64 {
	if m != nil {
		return m.SendIndex
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*BftSmartMessage) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _BftSmartMessage_OneofMarshaler, _BftSmartMessage_OneofUnmarshaler, _BftSmartMessage_OneofSizer, []interface{}{
		(*BftSmartMessage_Regular)(nil),
		(*BftSmartMessage_TimeToCut)(nil),
		(*BftSmartMessage_Connect)(nil),
		(*BftSmartMessage_Synchronize)(nil),
		(*BftSmartMessage_BftProxyConnect)(nil),
	}
}

func _BftSmartMessage_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*BftSmartMessage)
	// Type
	switch x := m.Type.(type) {
	case *BftSmartMessage_Regular:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Regular); err != nil {
			return err
		}
	case *BftSmartMessage_TimeToCut:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TimeToCut); err != nil {
			return err
		}
	case *BftSmartMessage_Connect:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Connect); err != nil {
			return err
		}
	case *BftSmartMessage_Synchronize:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Synchronize); err != nil {
			return err
		}
	case *BftSmartMessage_BftProxyConnect:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BftProxyConnect); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("BftSmartMessage.Type has unexpected type %T", x)
	}
	return nil
}

func _BftSmartMessage_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*BftSmartMessage)
	switch tag {
	case 1: // Type.regular
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BftSmartMessageRegular)
		err := b.DecodeMessage(msg)
		m.Type = &BftSmartMessage_Regular{msg}
		return true, err
	case 2: // Type.time_to_cut
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BftSmartMessageTimeToCut)
		err := b.DecodeMessage(msg)
		m.Type = &BftSmartMessage_TimeToCut{msg}
		return true, err
	case 3: // Type.connect
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BftSmartMessageConnect)
		err := b.DecodeMessage(msg)
		m.Type = &BftSmartMessage_Connect{msg}
		return true, err
	case 4: // Type.synchronize
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BftSmartMessageSynchronize)
		err := b.DecodeMessage(msg)
		m.Type = &BftSmartMessage_Synchronize{msg}
		return true, err
	case 5: // Type.bftProxyConnect
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BftProxyMessageConnect)
		err := b.DecodeMessage(msg)
		m.Type = &BftSmartMessage_BftProxyConnect{msg}
		return true, err
	default:
		return false, nil
	}
}

func _BftSmartMessage_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*BftSmartMessage)
	// Type
	switch x := m.Type.(type) {
	case *BftSmartMessage_Regular:
		s := proto.Size(x.Regular)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *BftSmartMessage_TimeToCut:
		s := proto.Size(x.TimeToCut)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *BftSmartMessage_Connect:
		s := proto.Size(x.Connect)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *BftSmartMessage_Synchronize:
		s := proto.Size(x.Synchronize)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *BftSmartMessage_BftProxyConnect:
		s := proto.Size(x.BftProxyConnect)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// BftSmartMessageRegular wraps a marshalled envelope.
type BftSmartMessageRegular struct {
	Payload   []byte                       `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	ConfigSeq uint64                       `protobuf:"varint,2,opt,name=config_seq,json=configSeq" json:"config_seq,omitempty"`
	Class     BftSmartMessageRegular_Class `protobuf:"varint,3,opt,name=class,enum=orderer.BftSmartMessageRegular_Class" json:"class,omitempty"`
}

func (m *BftSmartMessageRegular) Reset()                    { *m = BftSmartMessageRegular{} }
func (m *BftSmartMessageRegular) String() string            { return proto.CompactTextString(m) }
func (*BftSmartMessageRegular) ProtoMessage()               {}
func (*BftSmartMessageRegular) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BftSmartMessageRegular) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *BftSmartMessageRegular) GetConfigSeq() uint64 {
	if m != nil {
		return m.ConfigSeq
	}
	return 0
}

func (m *BftSmartMessageRegular) GetClass() BftSmartMessageRegular_Class {
	if m != nil {
		return m.Class
	}
	return BftSmartMessageRegular_UNKNOWN
}

// BftSmartMessageTimeToCut is used to signal to the orderers
// that it is time to cut block <block_number>.
type BftSmartMessageTimeToCut struct {
	BlockNumber uint64 `protobuf:"varint,1,opt,name=block_number,json=blockNumber" json:"block_number,omitempty"`
}

func (m *BftSmartMessageTimeToCut) Reset()                    { *m = BftSmartMessageTimeToCut{} }
func (m *BftSmartMessageTimeToCut) String() string            { return proto.CompactTextString(m) }
func (*BftSmartMessageTimeToCut) ProtoMessage()               {}
func (*BftSmartMessageTimeToCut) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BftSmartMessageTimeToCut) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

// BftSmartMessageConnect is posted by an orderer upon booting up.
type BftSmartMessageConnect struct {
	Payload   []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	StartFrom uint64 `protobuf:"varint,2,opt,name=start_from,json=startFrom" json:"start_from,omitempty"`
}

func (m *BftSmartMessageConnect) Reset()                    { *m = BftSmartMessageConnect{} }
func (m *BftSmartMessageConnect) String() string            { return proto.CompactTextString(m) }
func (*BftSmartMessageConnect) ProtoMessage()               {}
func (*BftSmartMessageConnect) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *BftSmartMessageConnect) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *BftSmartMessageConnect) GetStartFrom() uint64 {
	if m != nil {
		return m.StartFrom
	}
	return 0
}

// BftSmartMessageSynchronize is posted
type BftSmartMessageSynchronize struct {
	Payload       []byte                           `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	SyncStartFrom uint64                           `protobuf:"varint,2,opt,name=syncStartFrom" json:"syncStartFrom,omitempty"`
	MsgOffset     uint64                           `protobuf:"varint,3,opt,name=msgOffset" json:"msgOffset,omitempty"`
	BlockIndex    uint64                           `protobuf:"varint,4,opt,name=blockIndex" json:"blockIndex,omitempty"`
	Class         BftSmartMessageSynchronize_Class `protobuf:"varint,5,opt,name=class,enum=orderer.BftSmartMessageSynchronize_Class" json:"class,omitempty"`
	IsOver        bool                             `protobuf:"varint,6,opt,name=isOver" json:"isOver,omitempty"`
}

func (m *BftSmartMessageSynchronize) Reset()                    { *m = BftSmartMessageSynchronize{} }
func (m *BftSmartMessageSynchronize) String() string            { return proto.CompactTextString(m) }
func (*BftSmartMessageSynchronize) ProtoMessage()               {}
func (*BftSmartMessageSynchronize) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *BftSmartMessageSynchronize) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *BftSmartMessageSynchronize) GetSyncStartFrom() uint64 {
	if m != nil {
		return m.SyncStartFrom
	}
	return 0
}

func (m *BftSmartMessageSynchronize) GetMsgOffset() uint64 {
	if m != nil {
		return m.MsgOffset
	}
	return 0
}

func (m *BftSmartMessageSynchronize) GetBlockIndex() uint64 {
	if m != nil {
		return m.BlockIndex
	}
	return 0
}

func (m *BftSmartMessageSynchronize) GetClass() BftSmartMessageSynchronize_Class {
	if m != nil {
		return m.Class
	}
	return BftSmartMessageSynchronize_UNKNOWN
}

func (m *BftSmartMessageSynchronize) GetIsOver() bool {
	if m != nil {
		return m.IsOver
	}
	return false
}

// used when the bftproxy connect to replica
type BftProxyMessageConnect struct {
	Orderer string `protobuf:"bytes,1,opt,name=orderer" json:"orderer,omitempty"`
}

func (m *BftProxyMessageConnect) Reset()                    { *m = BftProxyMessageConnect{} }
func (m *BftProxyMessageConnect) String() string            { return proto.CompactTextString(m) }
func (*BftProxyMessageConnect) ProtoMessage()               {}
func (*BftProxyMessageConnect) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *BftProxyMessageConnect) GetOrderer() string {
	if m != nil {
		return m.Orderer
	}
	return ""
}

// LastOffsetPersisted is the encoded value for the Metadata message
// which is encoded in the ORDERER block metadata index for the case
// of the BftSmart-based orderer.
type BftSmartMessageMetadata struct {
	BlockIndex uint64 `protobuf:"varint,1,opt,name=blockIndex" json:"blockIndex,omitempty"`
	MsgOffset  uint64 `protobuf:"varint,2,opt,name=msgOffset" json:"msgOffset,omitempty"`
}

func (m *BftSmartMessageMetadata) Reset()                    { *m = BftSmartMessageMetadata{} }
func (m *BftSmartMessageMetadata) String() string            { return proto.CompactTextString(m) }
func (*BftSmartMessageMetadata) ProtoMessage()               {}
func (*BftSmartMessageMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *BftSmartMessageMetadata) GetBlockIndex() uint64 {
	if m != nil {
		return m.BlockIndex
	}
	return 0
}

func (m *BftSmartMessageMetadata) GetMsgOffset() uint64 {
	if m != nil {
		return m.MsgOffset
	}
	return 0
}

type BftSmartProxy struct {
	Offset   uint64           `protobuf:"varint,1,opt,name=offset" json:"offset,omitempty"`
	BfgMsg   *BftSmartMessage `protobuf:"bytes,2,opt,name=bfgMsg" json:"bfgMsg,omitempty"`
	NeedSync bool             `protobuf:"varint,3,opt,name=needSync" json:"needSync,omitempty"`
}

func (m *BftSmartProxy) Reset()                    { *m = BftSmartProxy{} }
func (m *BftSmartProxy) String() string            { return proto.CompactTextString(m) }
func (*BftSmartProxy) ProtoMessage()               {}
func (*BftSmartProxy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *BftSmartProxy) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *BftSmartProxy) GetBfgMsg() *BftSmartMessage {
	if m != nil {
		return m.BfgMsg
	}
	return nil
}

func (m *BftSmartProxy) GetNeedSync() bool {
	if m != nil {
		return m.NeedSync
	}
	return false
}

type SendResponse struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *SendResponse) Reset()                    { *m = SendResponse{} }
func (m *SendResponse) String() string            { return proto.CompactTextString(m) }
func (*SendResponse) ProtoMessage()               {}
func (*SendResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *SendResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type RecvResponse struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *RecvResponse) Reset()                    { *m = RecvResponse{} }
func (m *RecvResponse) String() string            { return proto.CompactTextString(m) }
func (*RecvResponse) ProtoMessage()               {}
func (*RecvResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *RecvResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*BftSmartMessage)(nil), "orderer.BftSmartMessage")
	proto.RegisterType((*BftSmartMessageRegular)(nil), "orderer.BftSmartMessageRegular")
	proto.RegisterType((*BftSmartMessageTimeToCut)(nil), "orderer.BftSmartMessageTimeToCut")
	proto.RegisterType((*BftSmartMessageConnect)(nil), "orderer.BftSmartMessageConnect")
	proto.RegisterType((*BftSmartMessageSynchronize)(nil), "orderer.BftSmartMessageSynchronize")
	proto.RegisterType((*BftProxyMessageConnect)(nil), "orderer.BftProxyMessageConnect")
	proto.RegisterType((*BftSmartMessageMetadata)(nil), "orderer.BftSmartMessageMetadata")
	proto.RegisterType((*BftSmartProxy)(nil), "orderer.BftSmartProxy")
	proto.RegisterType((*SendResponse)(nil), "orderer.SendResponse")
	proto.RegisterType((*RecvResponse)(nil), "orderer.RecvResponse")
	proto.RegisterEnum("orderer.BftSmartMessageRegular_Class", BftSmartMessageRegular_Class_name, BftSmartMessageRegular_Class_value)
	proto.RegisterEnum("orderer.BftSmartMessageSynchronize_Class", BftSmartMessageSynchronize_Class_name, BftSmartMessageSynchronize_Class_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Sender service

type SenderClient interface {
	// orderer send the request
	SendOrdererRequest(ctx context.Context, opts ...grpc.CallOption) (Sender_SendOrdererRequestClient, error)
}

type senderClient struct {
	cc *grpc.ClientConn
}

func NewSenderClient(cc *grpc.ClientConn) SenderClient {
	return &senderClient{cc}
}

func (c *senderClient) SendOrdererRequest(ctx context.Context, opts ...grpc.CallOption) (Sender_SendOrdererRequestClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Sender_serviceDesc.Streams[0], c.cc, "/orderer.Sender/SendOrdererRequest", opts...)
	if err != nil {
		return nil, err
	}
	x := &senderSendOrdererRequestClient{stream}
	return x, nil
}

type Sender_SendOrdererRequestClient interface {
	Send(*BftSmartMessage) error
	CloseAndRecv() (*SendResponse, error)
	grpc.ClientStream
}

type senderSendOrdererRequestClient struct {
	grpc.ClientStream
}

func (x *senderSendOrdererRequestClient) Send(m *BftSmartMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *senderSendOrdererRequestClient) CloseAndRecv() (*SendResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SendResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Sender service

type SenderServer interface {
	// orderer send the request
	SendOrdererRequest(Sender_SendOrdererRequestServer) error
}

func RegisterSenderServer(s *grpc.Server, srv SenderServer) {
	s.RegisterService(&_Sender_serviceDesc, srv)
}

func _Sender_SendOrdererRequest_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SenderServer).SendOrdererRequest(&senderSendOrdererRequestServer{stream})
}

type Sender_SendOrdererRequestServer interface {
	SendAndClose(*SendResponse) error
	Recv() (*BftSmartMessage, error)
	grpc.ServerStream
}

type senderSendOrdererRequestServer struct {
	grpc.ServerStream
}

func (x *senderSendOrdererRequestServer) SendAndClose(m *SendResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *senderSendOrdererRequestServer) Recv() (*BftSmartMessage, error) {
	m := new(BftSmartMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Sender_serviceDesc = grpc.ServiceDesc{
	ServiceName: "orderer.Sender",
	HandlerType: (*SenderServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendOrdererRequest",
			Handler:       _Sender_SendOrdererRequest_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "bftsmart.proto",
}

// Client API for Recver service

type RecverClient interface {
	// orderer recv response
	RecvOrdererResponse(ctx context.Context, opts ...grpc.CallOption) (Recver_RecvOrdererResponseClient, error)
}

type recverClient struct {
	cc *grpc.ClientConn
}

func NewRecverClient(cc *grpc.ClientConn) RecverClient {
	return &recverClient{cc}
}

func (c *recverClient) RecvOrdererResponse(ctx context.Context, opts ...grpc.CallOption) (Recver_RecvOrdererResponseClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Recver_serviceDesc.Streams[0], c.cc, "/orderer.Recver/RecvOrdererResponse", opts...)
	if err != nil {
		return nil, err
	}
	x := &recverRecvOrdererResponseClient{stream}
	return x, nil
}

type Recver_RecvOrdererResponseClient interface {
	Send(*BftSmartProxy) error
	CloseAndRecv() (*RecvResponse, error)
	grpc.ClientStream
}

type recverRecvOrdererResponseClient struct {
	grpc.ClientStream
}

func (x *recverRecvOrdererResponseClient) Send(m *BftSmartProxy) error {
	return x.ClientStream.SendMsg(m)
}

func (x *recverRecvOrdererResponseClient) CloseAndRecv() (*RecvResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(RecvResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Recver service

type RecverServer interface {
	// orderer recv response
	RecvOrdererResponse(Recver_RecvOrdererResponseServer) error
}

func RegisterRecverServer(s *grpc.Server, srv RecverServer) {
	s.RegisterService(&_Recver_serviceDesc, srv)
}

func _Recver_RecvOrdererResponse_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RecverServer).RecvOrdererResponse(&recverRecvOrdererResponseServer{stream})
}

type Recver_RecvOrdererResponseServer interface {
	SendAndClose(*RecvResponse) error
	Recv() (*BftSmartProxy, error)
	grpc.ServerStream
}

type recverRecvOrdererResponseServer struct {
	grpc.ServerStream
}

func (x *recverRecvOrdererResponseServer) SendAndClose(m *RecvResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *recverRecvOrdererResponseServer) Recv() (*BftSmartProxy, error) {
	m := new(BftSmartProxy)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Recver_serviceDesc = grpc.ServiceDesc{
	ServiceName: "orderer.Recver",
	HandlerType: (*RecverServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RecvOrdererResponse",
			Handler:       _Recver_RecvOrdererResponse_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "bftsmart.proto",
}

func init() { proto.RegisterFile("bftsmart.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 744 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x55, 0x6d, 0x8f, 0xda, 0x46,
	0x10, 0xc6, 0x04, 0x0c, 0x0c, 0x24, 0x41, 0x5b, 0x35, 0xb5, 0x4e, 0x7d, 0xb9, 0xb8, 0x4d, 0x45,
	0xa5, 0x08, 0x2a, 0xfa, 0x31, 0xaa, 0xaa, 0x1e, 0x22, 0x01, 0xa5, 0x40, 0xb2, 0xe6, 0x14, 0xa9,
	0x5f, 0x90, 0x5f, 0xc6, 0x06, 0x15, 0x7b, 0xb9, 0xdd, 0x75, 0x14, 0xfa, 0x7b, 0xfa, 0x33, 0xfa,
	0xa9, 0xbf, 0xac, 0xda, 0xb5, 0x0d, 0x1c, 0x1c, 0x77, 0xf9, 0xb6, 0x33, 0xfb, 0xcc, 0xc3, 0x33,
	0xf3, 0xcc, 0x1a, 0x78, 0xe2, 0x85, 0x52, 0xc4, 0x2e, 0x97, 0xdd, 0x0d, 0x67, 0x92, 0x91, 0x1a,
	0xe3, 0x01, 0x72, 0xe4, 0xf6, 0x7f, 0x8f, 0xe0, 0xe9, 0x55, 0x28, 0x1d, 0x75, 0x37, 0x41, 0x21,
	0xdc, 0x08, 0xc9, 0x2b, 0xa8, 0x71, 0x8c, 0xd2, 0xb5, 0xcb, 0x2d, 0xe3, 0xd2, 0xe8, 0x34, 0xfb,
	0xdf, 0x75, 0x73, 0x78, 0xf7, 0x08, 0x4a, 0x33, 0xd8, 0xa8, 0x44, 0x8b, 0x0a, 0x32, 0x80, 0xa6,
	0x5c, 0xc5, 0xb8, 0x90, 0x6c, 0xe1, 0xa7, 0xd2, 0x2a, 0x6b, 0x82, 0xe7, 0xe7, 0x08, 0xe6, 0xab,
	0x18, 0xe7, 0x6c, 0x90, 0xca, 0x51, 0x89, 0x36, 0x64, 0x11, 0x28, 0x05, 0x3e, 0x4b, 0x12, 0xf4,
	0xa5, 0xf5, 0xe8, 0x7e, 0x05, 0x83, 0x0c, 0xa6, 0x14, 0xe4, 0x15, 0xe4, 0x0d, 0x34, 0xc5, 0x36,
	0xf1, 0x97, 0x9c, 0x25, 0xab, 0xbf, 0xd1, 0xaa, 0x68, 0x82, 0xef, 0xcf, 0x11, 0x38, 0x7b, 0xe8,
	0xa8, 0x44, 0x0f, 0x2b, 0xc9, 0x5b, 0x78, 0xea, 0x85, 0xf2, 0x1d, 0x67, 0x9f, 0xb6, 0xf9, 0xcf,
	0x58, 0xd5, 0x53, 0x35, 0xfa, 0xfe, 0x44, 0xcd, 0x71, 0x25, 0xf9, 0x1a, 0x1a, 0xfe, 0xd2, 0x4d,
	0x12, 0x5c, 0x8f, 0x03, 0xcb, 0xbc, 0x34, 0x3a, 0x0d, 0xba, 0x4f, 0x90, 0x67, 0x60, 0x0a, 0x4c,
	0x02, 0xe4, 0x56, 0x4d, 0x5f, 0xe5, 0x91, 0xaa, 0x52, 0xa7, 0x71, 0x12, 0xe0, 0x27, 0xab, 0x7e,
	0x69, 0x74, 0x2a, 0x74, 0x9f, 0xb8, 0x32, 0xa1, 0x32, 0xdf, 0x6e, 0xd0, 0xfe, 0xd7, 0x80, 0x67,
	0x77, 0x3b, 0x43, 0x2c, 0xa8, 0x6d, 0xdc, 0xed, 0x9a, 0xb9, 0x81, 0xf6, 0xb2, 0x45, 0x8b, 0x90,
	0x7c, 0x03, 0xe0, 0xb3, 0x24, 0x5c, 0x45, 0x0b, 0x81, 0x37, 0xda, 0xa7, 0x0a, 0x6d, 0x64, 0x19,
	0x07, 0x6f, 0xc8, 0x2b, 0xa8, 0xfa, 0x6b, 0x57, 0x08, 0x6d, 0xc0, 0x93, 0xfe, 0x8b, 0x07, 0x56,
	0xa0, 0x3b, 0x50, 0x60, 0x9a, 0xd5, 0xd8, 0x2f, 0xa1, 0xaa, 0x63, 0xd2, 0x84, 0xda, 0xf5, 0xf4,
	0xed, 0x74, 0xf6, 0x61, 0xda, 0x2e, 0x11, 0x00, 0x73, 0x3a, 0xa3, 0x93, 0xdf, 0xff, 0x68, 0x1b,
	0xea, 0x3c, 0x98, 0x4d, 0x5f, 0x8f, 0xdf, 0xb4, 0xcb, 0xf6, 0xaf, 0x60, 0x9d, 0x5b, 0x0b, 0xf2,
	0x1c, 0x5a, 0xde, 0x9a, 0xf9, 0x7f, 0x2d, 0x92, 0x34, 0xf6, 0x30, 0x5b, 0xc8, 0x0a, 0x6d, 0xea,
	0xdc, 0x54, 0xa7, 0xec, 0xf7, 0x27, 0xcd, 0x17, 0x33, 0xbf, 0xb7, 0x79, 0x21, 0x5d, 0x2e, 0x17,
	0x21, 0x67, 0x71, 0xd1, 0xbc, 0xce, 0xbc, 0xe6, 0x2c, 0xb6, 0xff, 0x29, 0xc3, 0xc5, 0xf9, 0x3d,
	0xb9, 0x87, 0xf7, 0x07, 0x78, 0xac, 0x36, 0xc8, 0x29, 0x98, 0x72, 0xea, 0xdb, 0x49, 0xe5, 0x6a,
	0x2c, 0xa2, 0x59, 0x18, 0x0a, 0xcc, 0x16, 0xbc, 0x42, 0xf7, 0x09, 0xf2, 0x2d, 0x80, 0x6e, 0x2f,
	0x33, 0xbd, 0xa2, 0xaf, 0x0f, 0x32, 0xe4, 0xb7, 0xc2, 0x99, 0xaa, 0x76, 0xe6, 0xa7, 0xcf, 0xd8,
	0xec, 0x5b, 0xee, 0xa8, 0x65, 0x5b, 0x89, 0xd9, 0x47, 0xe4, 0x7a, 0x0f, 0xeb, 0x34, 0x8f, 0xec,
	0xde, 0x9d, 0xae, 0x35, 0xa1, 0x46, 0x87, 0xef, 0xaf, 0x87, 0xce, 0xbc, 0x6d, 0x90, 0x16, 0xd4,
	0xe9, 0xd0, 0x79, 0x37, 0x9b, 0x3a, 0xc3, 0x76, 0xd9, 0xee, 0xeb, 0xc9, 0xdf, 0xf1, 0x00, 0xd4,
	0x84, 0x72, 0x55, 0x7a, 0x42, 0x0d, 0xba, 0xfb, 0xe0, 0x7c, 0x80, 0xaf, 0x8e, 0x74, 0x4e, 0x50,
	0xba, 0x81, 0x2b, 0xdd, 0xa3, 0xc6, 0x8d, 0x93, 0xc6, 0x6f, 0x8d, 0xad, 0x7c, 0x34, 0x36, 0x3b,
	0x85, 0xc7, 0x05, 0xb1, 0x56, 0xa4, 0xda, 0x64, 0x19, 0x36, 0xa3, 0xca, 0x23, 0xf2, 0x33, 0x98,
	0x5e, 0x18, 0x4d, 0x44, 0x94, 0x7f, 0x9c, 0xac, 0xb3, 0xab, 0x9d, 0xe3, 0xc8, 0x05, 0xd4, 0x13,
	0xc4, 0x40, 0x0d, 0x54, 0xdb, 0x55, 0xa7, 0xbb, 0xd8, 0xfe, 0x11, 0x5a, 0x0e, 0x26, 0x01, 0x45,
	0xb1, 0x61, 0x89, 0x40, 0xfd, 0x92, 0xa5, 0x2b, 0x53, 0x91, 0x37, 0x9e, 0x47, 0x0a, 0x47, 0xd1,
	0xff, 0xf8, 0x10, 0xae, 0xef, 0x80, 0xe9, 0x64, 0x6f, 0x7f, 0x0c, 0x44, 0x9d, 0x66, 0x99, 0x38,
	0x8a, 0x37, 0x29, 0x0a, 0x49, 0xce, 0xaa, 0xbd, 0xf8, 0x72, 0x77, 0x73, 0x28, 0xc8, 0x2e, 0x75,
	0x8c, 0x3e, 0x05, 0x53, 0xfd, 0x38, 0x72, 0x32, 0x82, 0x2f, 0xd4, 0x69, 0x47, 0x5a, 0xa8, 0x39,
	0x61, 0xd5, 0x33, 0x3c, 0xe0, 0x3c, 0x14, 0xaf, 0x38, 0xaf, 0xae, 0xe1, 0x05, 0xe3, 0x51, 0x77,
	0xb9, 0xdd, 0x20, 0x5f, 0x63, 0x10, 0x21, 0xef, 0x86, 0xae, 0xc7, 0x57, 0x7e, 0xf6, 0x17, 0x23,
	0x8a, 0xca, 0x3f, 0x5f, 0x46, 0x2b, 0xb9, 0x4c, 0xbd, 0xae, 0xcf, 0xe2, 0xde, 0x01, 0xba, 0x97,
	0xa1, 0x7b, 0x19, 0xba, 0x97, 0xa3, 0x3d, 0x53, 0xc7, 0xbf, 0xfc, 0x1f, 0x00, 0x00, 0xff, 0xff,
	0x7b, 0x97, 0x60, 0x8e, 0xb2, 0x06, 0x00, 0x00,
}
